services:
  caspian_api:
    container_name: caspian-api
    image: teamnightsky/caspian-api:latest
    build:
      context: .
      target: caspian_api
    restart: unless-stopped
    ports: 
      - ${CASPIAN_PORT}:${CASPIAN_PORT}/tcp
    environment:
      PORT: ${CASPIAN_PORT}
      SUPABASE_KEY: ${SERVICE_ROLE_KEY}
      POSTGREST_URL: http://rest:3000
